import re
from typing import List
from backend.models.schemas import WebElement, LocatorType
 
 
# ──────────────────────────────────────────────────────────────
#  POM Class Generator
# ──────────────────────────────────────────────────────────────
def export_page_object(
    elements: List[WebElement],
    class_name: str = "PageObjects",
    base_url: str   = "",
) -> str:
    """
    Generate a complete Selenium Page Object Model (POM) class
    from a list of WebElement objects.
 
    Usage in test:
        page = PageObjects(driver)
        page.get_username_input().send_keys("admin")
        page.get_login_button().click()
    """
    lines = [
        '"""',
        f"Auto-generated Page Object Model — {class_name}",
        "Generated by: AI-Assisted Smart Locator Generator",
        '"""',
        "",
        "from selenium import webdriver",
        "from selenium.webdriver.common.by import By",
        "from selenium.webdriver.support.ui import WebDriverWait",
        "from selenium.webdriver.support import expected_conditions as EC",
        "from selenium.webdriver.remote.webelement import WebElement as SeleniumElement",
        "from typing import List",
        "",
        "",
        f"class {class_name}:",
        '    """',
        f"    Page Object Model for {base_url or 'the analyzed page'}.",
        "    All locators auto-generated and ranked by SmartLocator reliability engine.",
        '    """',
        "",
        "    # ── Locator constants ────────────────────────────────────",
    ]
 
    # First, emit all locator constants
    seen_names: set = set()
    method_map: list = []
 
    for el in elements:
        loc  = el.best_locator
        name = _method_name(el, seen_names)
        by   = "By.XPATH" if loc.locator_type == LocatorType.XPATH else "By.CSS_SELECTOR"
        const_name = f"_{name.upper()}_LOCATOR"
        lines.append(f"    {const_name} = ({by}, \"{loc.value}\")")
        method_map.append((name, const_name, el, loc))
 
    lines += [
        "",
        "    # ── Constructor ──────────────────────────────────────────",
        "    def __init__(self, driver: webdriver.Chrome, timeout: int = 10):",
        "        self.driver  = driver",
        "        self.wait    = WebDriverWait(driver, timeout)",
        "",
        "    # ── Navigation ───────────────────────────────────────────",
    ]
 
    if base_url:
        lines += [
            "    def open(self) -> None:",
            f'        """Navigate to the target page."""',
            f'        self.driver.get("{base_url}")',
            "",
        ]
 
    lines.append("    # ── Element accessors ────────────────────────────────────")
 
    for name, const_name, el, loc in method_map:
        score = round(loc.score * 100)
        lines += [
            "",
            f"    def get_{name}(self) -> SeleniumElement:",
            f'        """',
            f"        Locate <{el.tag}>{(' — ' + el.text[:40]) if el.text else ''}",
            f"        Strategy : {loc.strategy}  |  Reliability : {loc.reliability.upper()}  |  Score : {score}%",
            f'        """',
            f"        return self.wait.until(",
            f"            EC.presence_of_element_located(self.{const_name})",
            f"        )",
            "",
            f"    def click_{name}(self) -> None:",
            f'        """Click the <{el.tag}> element."""',
            f"        self.get_{name}().click()",
        ]
 
        if el.tag in ("input", "textarea"):
            lines += [
                "",
                f"    def type_{name}(self, text: str) -> None:",
                f'        """Clear and type into the <{el.tag}> element."""',
                f"        elem = self.get_{name}()",
                f"        elem.clear()",
                f"        elem.send_keys(text)",
            ]
 
    lines += [
        "",
        "    # ── Bulk helpers ─────────────────────────────────────────",
        "",
        f"    def get_all_locators(self) -> List[SeleniumElement]:",
        f'        """Return all locatable elements on the page."""',
        f"        return [",
    ]
    for name, *_ in method_map:
        lines.append(f"            self.get_{name}(),")
    lines += [
        "        ]",
        "",
        "    def is_page_loaded(self) -> bool:",
        '        """Check if at least one element is present."""',
        "        try:",
        f"            {f'self.get_{method_map[0][0]}()' if method_map else 'return True'}",
        "            return True",
        "        except Exception:",
        "            return False",
    ]
 
    return "\n".join(lines)
 
 
# ──────────────────────────────────────────────────────────────
#  Internal helpers
# ──────────────────────────────────────────────────────────────
def _method_name(el: WebElement, seen: set) -> str:
    """Derive a clean, unique Python method name from element data."""
    candidates = [
        el.attributes.get("data-testid", ""),
        el.attributes.get("data-test", ""),
        el.attributes.get("data-cy", ""),
        el.attributes.get("aria-label", ""),
        el.attributes.get("id", ""),
        el.attributes.get("name", ""),
        el.attributes.get("placeholder", ""),
        (el.text or "")[:30],
        f"{el.tag}_{el.element_index}",
    ]
    for cand in candidates:
        clean = re.sub(r"[^a-z0-9_]", "_", cand.lower().strip())
        clean = re.sub(r"_+", "_", clean).strip("_")[:40]
        if clean and clean not in seen:
            seen.add(clean)
            return clean
    # fallback: tag + index
    fb = f"{el.tag}_{el.element_index}"
    seen.add(fb)
    return fb